# Generated by Django 6.1.1 on 2026-10-01 11:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.PositiveIntegerField()),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator('^[A-Z]{2}$', 'State must be a 2-letter uppercase code.')])),
                ('rack_id', models.PositiveIntegerField()),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fuel_station',
                'ordering': ['opis_truckstop_id', 'id'],
                'indexes': [models.Index(fields=['opis_truckstop_id'], name='fuel_station_opis_id_idx'), models.Index(fields=['state'], name='fuel_station_state_idx'), models.Index(fields=['latitude', 'longitude'], name='fuel_station_coords_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('retail_price__gt', 0)), name='fuel_station_retail_price_positive')],
            },
        ),
    ]
